#!/bin/bash
mkdir -p tmp
outpath="tmp/readme-spec.coffee.md"
headerpath="docs/spec-header.coffee.md"
readmepath="README.md"
footerpath="docs/spec-footer.coffee.md"

echo > $outpath
cat $headerpath >> $outpath
echo >> $outpath
cat $readmepath >> $outpath
echo >> $outpath
cat $footerpath >> $outpath

NODE_PATH=$NODE_PATH:. ./node_modules/.bin/coffee -l $outpath
